Presentation/CutOutWiz.Web/Controllers/ClientController.cs
using CutOutWiz.Core.Utilities;
using CutOutWiz.Data;
using CutOutWiz.Services.DataService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CutOutWiz.Web.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class ClientController : BaseController
    {

        private readonly ICompanyService _companyService;
        public ClientController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public async Task<ActionResult> Index()
        {
            var company = await _companyService.GetAllCompany();
            return View(company);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: CompaniesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Company model)
        {
            try
            {
                //Validate Folder Name
                var folder = await _companyService.GetFolderByFolderName(model.FileRootFolderPath);

                if(folder.Count() == 0)
                {
                    model.CreatedDateUtc = DateTime.Now;
                    model.Status = StatusConstants.Active;
                    model.CreatedByContactId = CurrentLoggedInUser.UserId;

                    await _companyService.InsertCompany(model);
                    ViewBag.Message = "New client is created successfully!";
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Message = model.FileRootFolderPath+" is already exists!";
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CompaniesController/Edit/5
        public ActionResult Edit(int id)
        {
            var companyInfo = _companyService.GetCompanyById(id);
            var company = companyInfo.Result;
            return View(company);
        }

        // POST: CompaniesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Company model)
        {
            try
            {
                var updateInfo = _companyService.UpdateCompany(model);
                if (updateInfo != null)
                {
                    ViewBag.Message = "Update Successfully Done";
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Message = "Update Failed";
                return View();

            }
            catch
            {
                return View();
            }
        }

        // GET: CompaniesController/Delete/5
        public ActionResult Delete(int id)
        {
            _companyService.DeleteCompany(id);
            return RedirectToAction(nameof(Index));
        }


        // POST: CompaniesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/CutOutWiz.Web/Controllers/ImagesController.cs
using CutOutWiz.Core.Utilities;
using CutOutWiz.Data;
using CutOutWiz.Data.Models.ApprovalTool;
using CutOutWiz.Services.ApprovalTool;
using CutOutWiz.Services.DataService;
using CutOutWiz.Services.LogService;
using CutOutWiz.Services.MessageService;
using CutOutWiz.Services.StorageService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CutOutWiz.Web.Controllers
{
    [Authorize(Roles = "Client")]
    public class ImagesController : BaseController
    {
        public readonly IAwsService _awsService;
        private readonly IConfiguration _configuration;
        private readonly IFileTrackingService _fileFracking;
        private readonly IApprovalToolCommonService _approvalToolCommonService;
        private readonly IEmailSenderService _emailSenderSerice;
        private readonly ILogService _logger;

        public ImagesController(IAwsService awsService,
            IConfiguration configuration,
            IFileTrackingService fileFracking,
            IApprovalToolCommonService approvalToolCommonService,
            IEmailSenderService emailSenderSerice,
            ILogService logger)
        {
            _awsService = awsService;
            _configuration = configuration;
            _fileFracking = fileFracking;
            _emailSenderSerice = emailSenderSerice;
            _approvalToolCommonService = approvalToolCommonService;
            _logger = logger;
        }

        public IActionResult Test()
        {
            return View();
        }

        public IActionResult Index()
        {
            _logger.Log($"User {CurrentLoggedInUser.Username} landed on directory browsing page");

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetTreeData(string path)
        {
            var folderPath = path;
            //if (!string.IsNullOrWhiteSpace(path))
            //{
            //    path = path.TrimStart('/');
            //}

            //FTP Server
            //FtpService ftpReader = new FtpService();
            //var result = ftpReader.ReadDirectoriesAsync(path);

            //Demo data
            //var result = GetDemoFolders();

            //S3 Server            
            var clientFolderPrefix = CurrentLoggedInUser.ClientRootFolderPath;
            var addApprovalPath = false;

            string delimiter = String.Empty;

            if (string.IsNullOrWhiteSpace(folderPath))
            {
                delimiter = "/";
                folderPath = $"{clientFolderPrefix}/";
                addApprovalPath = true;
            }
            else
            {
                delimiter = "/";
                folderPath = $"{folderPath}/";
            }

            var awsCredentials = _approvalToolCommonService.GetAwsCredentials();
            var response = await _awsService.GetDirectories(awsCredentials, folderPath, delimiter);

            if (response.Result == null)
            {
                response.Result = new List<Data.Node>();
            }

            //Add For Approval Path
            if (path != null && path.ToCharArray().Count(c => c == '/') == 1)
            {
                foreach (var folder in response.Result)
                {
                    folder.key = $"{folder.key}/For Approval";
                }
            }

            return Json(response.Result);
        }

        [HttpGet]
        public async Task<IActionResult> GetImagesByPath(string path, int imgWidth = 120, int imgHeight = 0)
        {
            _logger.Log($"User {CurrentLoggedInUser.Username} viewing images");

            if (!string.IsNullOrWhiteSpace(path))
            {
                //path= Uri.EscapeDataString(path);
                //path = WebUtility.UrlEncode(path);
                path = path.TrimStart('/');
            }

            //Ftp Files
            //FtpService ftpReader = new FtpService();
            //var response = ftpReader.ReadFilesAsync(path);

            //Demo files
            //var response = GetDemoImages();

            //S3 Files
            var awsCredentials = _approvalToolCommonService.GetAwsCredentials();
            var response = await _awsService.GetFilesByPath(awsCredentials, path);

            if (response.Result == null || !response.Result.Any())
            {
                response.Result = new List<Data.DriveImage>();
                return Json(response);
            }

            //Set thomnail image links if result found
            string imageHandlerBaseUrl = _configuration["AwsSettings:ImageHandlerBaseUrl"];

            var fullBasePath = $"{imageHandlerBaseUrl}filters:background_color(gainsboro)/fit-in/{imgWidth}x{imgHeight}/";

            List<string> ImageExtensions = new List<string> { ".JPG", ".JPEG", ".JPE", ".BMP", ".GIF", ".PNG", ".PSD", ".TIF", ".TIFF", ".WEBP", ".SVG", ".CR2", ".NEF" };
            var newImageList = new List<DriveImage>();

        //https://dprp12nc61odv.cloudfront.net/fit-in/200x200/Client%201/Brand%202/To%20Process/A163614-ADI-Catalog-FTW/image_2608801_b41bafab.png
            foreach (var img in response.Result)
            {
                var fileName = _approvalToolCommonService.GetFileNameFromPath(img.RawImagePath ?? "");

                //get images only
                if (!ImageExtensions.Contains(Path.GetExtension(fileName).ToUpperInvariant()))
                {
                    continue;
                }
                img.FullPath = $"{fullBasePath}{img.Path}";               
               
                var directoryName = _approvalToolCommonService.GetParentDirectory(img.RawImagePath ?? "");
                var fileNameWithoutIssueFolder = _approvalToolCommonService.GetActualDirectoryPathWithoutIssueFolder(directoryName);
                img.RawImagePath = $"{fullBasePath}{fileNameWithoutIssueFolder}/{fileName}";

                newImageList.Add(img);
            }

            response.Result = newImageList;
            return Json(response);
        }

        [HttpPost]
        public async Task<ActionResult> MoveFiles(ImageMoveRequestModel model)
        {            
            var moveResponse = new Response<List<ImageMoveResponseModel>>();
            var imagesMoveResponse = new List<ImageMoveResponseModel>();
            //validation
            if (model == null || model.SelectedImages == null)
            {
                moveResponse.Message = "Please select atleast 1 image.";
                return Json(moveResponse);
            }

            //Move Files
            var awsCredentials = _approvalToolCommonService.GetAwsCredentials();
            var selectedImages = model.SelectedImages.Split('|');
            
            foreach (var imgPath in selectedImages)
            {
                var fileMoveResponse = new Response<bool>();

                if (model.ActionType == ApprovalToolActionTypeConstants.Accepted)
                {
                    var destination = _approvalToolCommonService.GetDestinationPath(model.ActionType, imgPath);
                    fileMoveResponse = await _awsService.MoveFile(awsCredentials, imgPath, destination);
                }
                else if (model.ActionType == ApprovalToolActionTypeConstants.Rejected)
                {
                    fileMoveResponse = await _awsService.DeleteFile(awsCredentials, imgPath);
                }

                var fileName = imgPath.Split('/').Last();

                if (fileMoveResponse.IsSuccess)
                {
                    imagesMoveResponse.Add(new ImageMoveResponseModel { FileName = fileName, IsSuccess = true });
                }
                else
                {
                    imagesMoveResponse.Add(new ImageMoveResponseModel { FileName = fileName, IsSuccess = false, Message = fileMoveResponse.Message });
                }
            }
                        
            //Add Comments
            if (model.ActionType == ApprovalToolActionTypeConstants.Rejected && !string.IsNullOrWhiteSpace(model.Comments))
            {                
                var destination = _approvalToolCommonService.GetDestinationIssueFolderPath(model.SelectedImages);

                var comments = _approvalToolCommonService.GetFormattedComments(model);
                var postFixDatePart = DateTime.Now.ToString("dd MMMM yyyy HH mm ss");
                var commentFilePath = $"{destination}comment_{postFixDatePart}.txt";
                await _awsService.AddText(awsCredentials, commentFilePath, comments);                
            }

            moveResponse.IsSuccess = true;
            moveResponse.Result = imagesMoveResponse;

            //Message for client
            moveResponse.Message = _approvalToolCommonService.GetResponseMessage(imagesMoveResponse,model.ActionType);

            //Add accepted or rejected images in database
            var fileTracking = _approvalToolCommonService.AddFileTrackingRecord(model, CurrentLoggedInUser, awsCredentials);
            await _fileFracking.InsertFileTracking(fileTracking);

            //Send Email to Admin
            var emailMessage = _emailSenderSerice.GetEmailMessage(fileTracking);
            var emailSendResponse = await _emailSenderSerice.SendEmail(emailMessage);

            return Json(moveResponse);
        }

        #region Markup Image
        [HttpGet]
        public async Task<IActionResult> GetBase64ByPath(string path, int imgWidth = 800, int imgHeight = 0)
        {
            try
            {
                _logger.Log($"User {CurrentLoggedInUser.Username} opening markup");

                string imageHandlerBaseUrl = _configuration["AwsSettings:ImageHandlerBaseUrl"];
                var fullBasePath = $"{imageHandlerBaseUrl}fit-in/{imgWidth}x{imgHeight}/";

                if (path.EndsWith(".TIFF"))
                {
                    fullBasePath = fullBasePath.Replace(imageHandlerBaseUrl, imageHandlerBaseUrl + "filters:autojpg()/");
                }
                

Presentation/CutOutWiz.Web/Controllers/IssuesController.cs
using CutOutWiz.Core.Utilities;
using CutOutWiz.Services.DataService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CutOutWiz.Web.Controllers
{
    [Authorize(Roles ="SuperAdmin")]
    public class IssuesController : BaseController
    {
        private readonly IFileTrackingService _fileTracking;

        public IssuesController(IFileTrackingService fileTracking)
        {
            _fileTracking=fileTracking;
        }

        // GET: IssuesController
        public async Task<ActionResult> Index()
        {
            var issues = await _fileTracking.GetFileTrackingByCompanyId(CurrentLoggedInUser.CompanyId ?? 0, ApprovalToolActionTypeConstants.Rejected);
            return View(issues);
        }

        // GET: IssuesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: IssuesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IssuesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: IssuesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: IssuesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: IssuesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: IssuesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/CutOutWiz.Web/Views/Shared/_GeneralNotificationModalPartial.cshtml
<div class="modal fade notification-modal" id="GeneralNotificationModal" tabindex="-1" role="dialog" aria-labelledby="GeneralNotificationModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom">
                <h5 class="modal-title">Notification</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="notificationMessage">
                    <div class="text-center"><div class="spinner-border spinner-border-sm text-primary"></div></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary mr-1" id="btnConfimationOK" action=""><span class="fal fa-check mr-1"></span>Confirm</button>
                <button id="btnCloseModal" type="button" class="btn btn-secondary" data-bs-dismiss="modal"><span class="fal fa-times mr-1"></span>Ok</button>
            </div>
        </div>
    </div>
</div>

Presentation/CutOutWiz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="robots" content="noindex,nofollow">
      <title>Approval Tool</title>
      <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.png">
     
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
      <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
      <link href="~/css/style.css" rel="stylesheet" asp-append-version="true">
      <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true"/>

      @await RenderSectionAsync("Styles", required: false)

   </head>
   <body>
      <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
         data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
         <!-- Start Topbar header -->
         <header class="topbar" data-navbarbg="">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
               class="ti-menu ti-close"></i></a>
         </header>
         <!-- ============================================================== -->
         <!-- End Topbar header -->
         <!-- ============================================================== -->
         <!-- ============================================================== -->
         <!-- Left Sidebar -->
         <!-- ============================================================== -->
        <partial name="_Sidebar" />
         <div class="page-wrapper">
            <div class="page-breadcrumb">
               @RenderBody()
            </div>
            <!--End of  right section-->

            </div>

             <footer class="mt-3">
            
         </footer>
       </div>
      <partial name="_GeneralNotificationModalPartial" />

      <script src="~/lib/jquery/dist/jquery.min.js"></script>
      <!-- Bootstrap tether Core JavaScript -->
      <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
      <!--Menu sidebar -->
      <script src="~/js/custom.js"></script>
      <script src="~/js/site.js"></script>

      @await RenderSectionAsync("Scripts", required: false)

      <!--chartis chart-->
      <script>
         var toggler = document.getElementsByClassName("caret");
         var i;
         
         for (i = 0; i < toggler.length; i++) {
           toggler[i].addEventListener("click", function() {
             this.parentElement.querySelector(".nested").classList.toggle("active");
             this.classList.toggle("caret-down");
           });
         }
      </script>
      <script>
         function selectAll(status) {
            $('input[name=selectedId]').each(function(){
               $(this).prop('checked', status);
            });
         }
      </script>
   </body>
</html>

Presentation/CutOutWiz.Web/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CutOutWiz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CutOutWiz.Web.styles.css" asp-append-version="true" />

     @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CutOutWiz</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="Index">Images</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Issues" asp-action="Index">Issues</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CutOutWiz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <partial name="_GeneralNotificationModalPartial" />

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/CutOutWiz.Web/Views/Shared/_LayoutSecurity.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CutOutWiz.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CutOutWiz.Web.styles.css" asp-append-version="true" />

     @await RenderSectionAsync("Styles", required: false)
</head>
<body>
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>